[fix]

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -5,52 +5,52 @@ on:
     types: [opened, synchronize]
 
 jobs:
-  ut_pr:
+  check-diff-app:
     runs-on: ubuntu-latest
-
+    
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+    - name: Checkout repository
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: 0  # これにより全履歴がフェッチされる
 
-      - name: Fetch all branches
-        run: git fetch origin main
+    - name: Fetch remote main branch
+      run: git fetch origin main
 
-      - name: Check for branch name with regex
-        id: check_branch
-        run: |
-          if [[ "${{ github.head_ref }}" =~ ^feature/LETRO-[0-9]+$ ]]; then
-            echo "target_branch=true" >> $GITHUB_ENV
-          else
-            echo "target_branch=false" >> $GITHUB_ENV
-          fi
+    - name: Check for branch name with regex
+      id: check_branch
+      run: |
+        if [[ "${{ github.head_ref }}" =~ ^feature/LETRO-[0-9]+$ ]]; then
+          echo "target_branch=true" >> $GITHUB_ENV
+        else
+          echo "target_branch=false" >> $GITHUB_ENV
+        fi
 
-      - name: Check for changes in app directory
-        id: check_changes
-        run: |
-          if [[ "${{ env.target_branch }}" == "true" ]]; then
-            if git diff --name-only origin/main...${{ github.sha }} | grep '^app/'; then
-              echo "changes_in_app=true" >> $GITHUB_ENV
-            else
-              echo "changes_in_app=false" >> $GITHUB_ENV
-            fi
+    - name: Check for changes in app directory
+      id: check_changes
+      run: |
+        if [[ "${{ env.target_branch }}" == "true" ]]; then
+          if git diff --name-only origin/main...${{ github.sha }} | grep '^app/'; then
+            echo "changes_in_app=true" >> $GITHUB_ENV
           else
             echo "changes_in_app=false" >> $GITHUB_ENV
           fi
+        else
+          echo "changes_in_app=false" >> $GITHUB_ENV
+        fi
 
-      - name: Fail if changes found in app directory
-        if: env.changes_in_app == 'true'
-        run: |
-          echo "Changes found in app directory. Closing pull request."
-          echo "::set-output name=result::failure"
-          exit 1
+    - name: Fail if changes found in app directory
+      if: env.changes_in_app == 'true'
+      run: |
+        echo "Changes found in app directory. Closing pull request."
+        echo "::set-output name=result::failure"
+        exit 1
 
-      - name: Add comment and close PR
-        if: steps.check-path.outputs.result == 'failure'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          curl -s -H "Authoization: token $GITHUB_TOKEN" \
-            -x POST -d "{\"body\":\"Pull request closed due to changes in app directory.\", \"state\":\"closed\"}" \
-            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}"
+    - name: Add comment and close PR
+      if: steps.check-path.outputs.result == 'failure'
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        curl -s -H "Authorization: token $GITHUB_TOKEN" \
+             -X POST -d "{\"body\":\"Pull request closed due to changes in app directory.\", \"state\":\"closed\"}" \
+             "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}"
